Description: >
  Cloudfront distribution for django-polls

Parameters:
  OriginURL:
    Description: Origin URL
    Type: String

  WorkflowID:
    Description: CircleCI Workflow ID
    Type: String

Resources:

  DjangoCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:  
      CachePolicyConfig:
        DefaultTTL: 86400
        MaxTTL: 31536000
        MinTTL: 1
        Name: DjangoCachePolicyConfig
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: false
          CookiesConfig:
            CookieBehavior: whitelist
            Cookies:
              - csrftoken
              - csrfmiddlewaretoken
              - _app_session
          HeadersConfig:
            HeaderBehavior: whitelist
            Headers:
              - Origin
              - Referer
          QueryStringsConfig:
            QueryStringBehavior: none
  
  DjangoPollsDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub ${OriginURL}
            Id: DjangoPollsCustomOrigin
            CustomOriginConfig:
              HTTPPort: '8000'
              OriginProtocolPolicy: http-only
        Enabled: True
        DefaultCacheBehavior:
          CachePolicyId: !Ref DjangoCachePolicy
          AllowedMethods:
            - GET
            - HEAD
            - DELETE
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: DjangoPollsCustomOrigin
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: Circle CI Workflow ID for Django-Polls EKS Cluster
    Export:
      Name: WorkflowID
