apiVersion: apps/v1
# Based on examples at:
# https://towardsdatascience.com/kubernetes-application-deployment-with-aws-eks-and-ecr-4600e11b2d3c
# https://k8s.io/examples/pods/private-reg-pod.yaml
kind: Deployment
metadata:
  name: django-polls-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-polls
  template:
    metadata:
      labels:
        app: django-polls
    spec:
      containers:
        - name: django-polls
          image: 429593792117.dkr.ecr.us-east-1.amazonaws.com/django-polls-repo:latest
          envFrom:
          - secretRef:
              name: django-polls-secret
          ports:
            - containerPort: 8000
