version: 2.1

#executors:
#  docker-publisher:
#    environment:
#      IMAGE_NAME: devopshiker42/django-polls:latest
#    docker:
#      - image: circleci/buildpack-deps:stretch

jobs:
  qa:
    docker:
      - image: cimg/python:3.8.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            sudo chmod +x /bin/hadolint

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

      - run:
          name: run tests
          command: |
            make test

workflows:
  default:
    jobs:
      - qa
#      - docker-build:
#          requires:
#            - qa
#          filters:
#            branches:
#              only: master
#      - docker-publish-latest:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master
